# Generated by Django 4.2.9 on 2024-01-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='materials_provided',
        ),
        migrations.AlterField(
            model_name='customer',
            name='DOB',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.CharField(choices=[('Ekm', 'Edapally'), ('Ekm', 'Vytilla'), ('T', 'Chavakkad'), ('T', 'Irinjalakuda'), ('K', 'chinnakada'), ('k', 'kottiyam')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Ekm', 'Ernakulam'), ('T', 'Thrissur'), ('K', 'kollam')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
