# Generated by Django 4.2.9 on 2024-01-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baankapp', '0003_alter_customer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='materials_provided',
            field=models.BooleanField(choices=[('credit_card', 'Credit card'), ('debit_card', 'Debit card'), ('cheque_book', 'Cheque book')], default=False, max_length=120),
        ),
    ]
