# Generated by Django 4.2.9 on 2024-01-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baankapp', '0005_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_type',
            field=models.BooleanField(choices=[('Savings', 'Savings Account'), ('Current', 'Current Account')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.BooleanField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=False, max_length=1),
        ),
    ]
