# Generated by Django 4.2.9 on 2024-01-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baankapp', '0006_alter_customer_account_type_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings Account'), ('Current', 'Current Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5),
        ),
    ]
