# Generated by Django 4.2.9 on 2024-01-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baankapp', '0011_alter_customer_materials_provided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.AddField(
            model_name='material',
            name='materials_provided',
            field=models.CharField(choices=[('credit_card', 'Credit card'), ('debit_card', 'Debit card'), ('cheque_book', 'Cheque book')], default=False, max_length=255),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='materials_provided',
        ),
        migrations.AddField(
            model_name='customer',
            name='materials_provided',
            field=models.ManyToManyField(to='baankapp.material'),
        ),
    ]
