# Generated by Django 4.2.9 on 2024-01-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baankapp', '0012_remove_material_name_material_materials_provided_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='materials_provided',
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
