# Generated by Django 4.2.9 on 2024-01-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baankapp', '0014_remove_customer_materials_provided_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='materials_provided',
        ),
    ]
