# Generated by Django 4.2.9 on 2024-01-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baankapp', '0015_remove_customer_materials_provided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
    ]
